question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "Honeybees can recognize human faces.", "answer": "True"},
    {"text": "A day on Venus is longer than its year.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Bananas are berries, but strawberries aren't.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "The tongue is the strongest muscle in the human body.", "answer": "False"},
    {"text": "Penguins have knees.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The average person spends 6 months of their lifetime waiting for red lights to turn green.", "answer": "True"},
    {"text": "A cockroach can live for several weeks without its head.", "answer": "True"},
    {"text": "The moon is perfectly spherical.", "answer": "False"},
    {"text": "All polar bears are left-handed.", "answer": "False"},
    {"text": "The inventor of the Pringles can was buried in a Pringles can.", "answer": "True"},
    {"text": "Rats and horses can't vomit.", "answer": "True"}
]